name: ESP32 Builder

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      WORKFLOW_BUILD_TYPE:
        description: 'Build type'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - production
      WORKFLOW_UPLOAD_TO_S3:
        description: 'Upload to S3?'
        required: true
        type: boolean
        default: false

env:
  DEFAULT_BUILD_TYPE: development
  DEFAULT_UPLOAD_TO_S3: true
  S3_CATALOG: awesome_catalog

jobs:
  build:
    name: Test test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set environment variables
        id: Set_variables
        run: |
          echo "${{ github.event.inputs.WORKFLOW_BUILD_TYPE }}"
          echo "${{ env.DEFAULT_BUILD_TYPE }}"
          echo "${{ github.event.inputs.WORKFLOW_UPLOAD_TO_S3 }}"
          echo "${{ env.DEFAULT_UPLOAD_TO_S3 }}"
          echo "BUILD_TYPE=${{ github.event.inputs.WORKFLOW_BUILD_TYPE || env.DEFAULT_BUILD_TYPE }}" >> $GITHUB_ENV
          echo "UPLOAD_TO_S3=${{ github.event.inputs.WORKFLOW_UPLOAD_TO_S3 || env.DEFAULT_UPLOAD_TO_S3 }}" >> $GITHUB_ENV
          echo "${{ env.BUILD_TYPE }}"
          echo "${{ env.UPLOAD_TO_S3 }}"

      - name: Change S3 folder when manuallt triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "S3_CATALOG=manual_catalog" >> $GITHUB_ENV
  
      - name: Use environment variables
        run: |
          echo "${{ env.BUILD_TYPE }}"
          echo "${{ env.UPLOAD_TO_S3 }}"
          echo "${{ env.S3_CATALOG }}"

      - name: Upload to S3
        if: env.UPLOAD_TO_S3 == 'true'
        run: echo "Uploading to S3 wwoho!"
