name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  deploy-stable:
    runs-on: ubuntu-latest
    environment: stable
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: 'Download artifacts v4'
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          github-token: ${{ secrets.ARTIFACT_PAT }} # token with actions:read permissions on target repo
          repository: EasyServ-Kenny/gh-actions
          run-id: ${{ github.event.workflow_run.id }}
    
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "my-artifact"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/my-artifact.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip my-artifact.zip
        
      - name: Deploy to stable
        run: |    
          echo Deploying
          ls
          echo Pushing to stable $KNY_VAR ${{ vars.KNY_VAR }}
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-stable]
    steps:
      - name: Deploy to prod
        run: echo Pushing to prod $KNY_VAR ${{ vars.KNY_VAR }}
