name: Deploy
run-name: Deploy of ${{ github.event.workflow_run.name }} ${{ github.event.workflow_run.run_number }} - ${{ github.event.workflow_run.display_title }}

env:
  PRODUCT_NAME: gh-actions-product

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:

  write-context:
    runs-on: ubuntu-latest
    steps:
    - name: Inspect contexts
      run: |
        echo "The github context is:"
        echo "${{ toJson(github) }}"
        echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW


  deploy-unstable:
    runs-on: ubuntu-latest
    environment: unstable
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: 'Download artifacts from CI workflow'
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.PRODUCT_NAME }}*
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: 'Deploy'
        run: | 
          cat version.json
          echo "NOWUNSTABLE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - run: echo $NOWUNSTABLE
          

  deploy-stable:
    runs-on: ubuntu-latest
    environment: stable
    needs: [deploy-unstable]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:        
      - name: 'Deploy'
        run: | 
          echo "NOWSTABLE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - run: echo $NOWSTABLE

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-stable]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:        
      - name: 'Deploy'
        run: | 
          echo "NOWPROD=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - run: echo $NOWPROD
