name: Deploy
run-name: Deploy of ${{ github.event.workflow_run.name }} ${{ github.event.workflow_run.run_number }} - ${{ github.event.workflow_run.display_title }}

env:
  PRODUCT_NAME: gh-actions-product

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:

  write-context:
    runs-on: ubuntu-latest
    steps:
    - name: Inspect contexts
      run: |
        echo "The github context is:"
        echo "${{ toJson(github) }}"

  deploy-unstable:
    runs-on: ubuntu-latest
    environment: unstable
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: 'Download artifacts from CI workflow'
        uses: actions/download-artifact@v4
        with:
          # pattern: ${{ env.PRODUCT_NAME }}*
          pattern: my-artifact
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: EasyServ-Kenny/gh-actions
          run-id: ${{ github.event.workflow_run.id }}

      - name: 'Unzip artifact'
        run: |
          ls
          unzip gh-actions-release.zip
          ls

  deploy-stable-no-pipeline:
    runs-on: ubuntu-latest
    environment: stable
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:        
      - name: Deploy to stable
        run: |
          echo Deploying

  deploy-prod-no-pipeline:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:        
      - name: Deploy to prod
        run: |
          echo Deploying


  deploy-stable:
    runs-on: ubuntu-latest
    environment: stable
    needs: [deploy-unstable]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: 'Download artifacts from CI workflow'
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.PRODUCT_NAME }}*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: EasyServ-Kenny/gh-actions
          run-id: ${{ github.event.workflow_run.id }}

      - name: 'Unzip artifact'
        run: |
          ls
          unzip ${{ env.PRODUCT_NAME }}*
          ls
        
      - name: Deploy to stable
        run: |
          echo Deploying
          ls
          echo Pushing to stable $KNY_VAR ${{ vars.KNY_VAR }}

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deploy-stable]
    steps:
      - name: Deploy to prod
        run: echo Pushing to prod $KNY_VAR ${{ vars.KNY_VAR }}
