# This is a basic workflow to help you get started with Actions

name: CI-test

env:
  PRODUCT_NAME: kenny-test
  AWS_S3_BUILD_BUCKET: test-kenny-easyserv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: unstable
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Zip package
        run: |
          echo Build build > package.txt
          zip package.zip package.txt 

      - name: Upload artifact to github actions
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: package.zip

  deploy-stable:
    runs-on: ubuntu-latest
    environment: stable
    needs: build
    steps:      
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Deploy to next stable
        run: |    
          echo ======
          ls
          echo Pushing to stable $KNY_VAR ${{ vars.KNY_VAR }}
          unzip package.zip
          echo Unzipped done
          echo =====
          ls
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [build, deploy-stable]
    
    steps:
      - name: Deploy to prod
        run: echo Pushing to prod $KNY_VAR ${{ vars.KNY_VAR }}
