# This is a basic workflow to help you get started with Actions

name: Build

env:
  PRODUCT_NAME: gh-actions-product

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set environment variables
        id: Set_variables
        run: |
          echo "BUILD_VERSION=$(date --utc +%Y-%m-%d)-build-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "BUILD_NAME=${{ env.PRODUCT_NAME }}_$(date --utc +%Y-%m-%d)-build-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "BUILD_SHA1=$(git log -1 --format='%H')" >> $GITHUB_ENV

      - name: Create package
        run: |
          echo "{\"build\": \"${{ env.BUILD_VERSION }}\", \"sha1\": \"${{ env.BUILD_SHA1 }}\"}" > sversion.json
          echo Build build > package.txt
          zip gh-actions-release.zip package.txt 

      - name: Upload artifact to github actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: gh-actions-release.zip
