name: Build
env:
  PRODUCT_NAME: gh-actions-product

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:      
      - uses: actions/checkout@v3
      
      - name: Set environment variables
        id: Set_variables
        run: |
          echo "BUILD_VERSION=$(date --utc +%Y-%m-%d)-build-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "BUILD_NAME=${{ env.PRODUCT_NAME }}_$(date --utc +%Y-%m-%d)-build-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "BUILD_SHA1=$(git log -1 --format='%H')" >> $GITHUB_ENV

      - name: Create package
        run: |
          mkdir deploy
          echo "{\"build\": \"${{ env.BUILD_VERSION }}\", \"sha1\": \"${{ env.BUILD_SHA1 }}\"}" > deploy/version.json
          echo Build build > deploy/package.txt

      - name: Upload artifact to github actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: deploy/*
    
      - run: gh workflow run manual-deploy.yml -f build=${{ env.BUILD_VERSION }} -f enviroment=unstable
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
