on:
  workflow_call:
    inputs:
      awesome:
        required: true
        type: string
    
jobs:
  deploy:
    environment: stable
    name: Deploy my app
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{ inputs.awesome }}
