on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build version'
        required: true
      environment:
        description: 'Target environment'
        type: environment
        required: true

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          environment: unstable
