on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build version'
        required: true
      environment:
        description: 'Target environment'
        type: environment
        required: true

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}
          owner: Easyserv-Kenny
          repo: gh-actions
          run_id: 7272479767
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"



# /repos/{owner}/{repo}/actions/runs/{run_id}
